server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 2MB

upload:
  allow-types: [ "text/plain" ]